import { corridorFor } from "@/lib/derive/corridor";
import { getOdishaDistricts, getOdishaState, getSyntheticAssets } from "@/lib/geo/load";
import type { Frame, Scenario } from "@/types/scenario";
import type { MapProjection } from "./project";
export type Theme = { bg: string; line: string; lineStrong: string; fg: string; fg2: string; fg3: string; observed: string; forecast: string; risk: string };
export type MapState = { scenario: Scenario; frame: Frame; time: number; selected: string | null; layers: Record<string, boolean>; mode: "radar" | "satellite"; decomposition: boolean; sensorOff: Record<string, boolean>; projection: MapProjection; width: number; height: number; theme: Theme; reduced: boolean };
export interface Layer { id: string; static?: boolean; draw(ctx: CanvasRenderingContext2D, state: MapState, now: number): void; }
const path = (ctx: CanvasRenderingContext2D, points: [number, number][], state: MapState, now: number, close = true) => { ctx.beginPath(); points.forEach((p, i) => { const [x, y] = state.projection.project(p); i ? ctx.lineTo(x, y) : ctx.moveTo(x, y); }); if (close) ctx.closePath(); };
const ring = (geometry: { type: string; coordinates: unknown }) => geometry.type === "Polygon" ? geometry.coordinates as [number, number][][] : (geometry.coordinates as [number, number][][][]).flat();
export const graticule: Layer = { id: "graticule", static: true, draw(ctx, s, now) { const [w, so, e, n] = s.scenario.region.bbox; ctx.strokeStyle = s.theme.line; ctx.globalAlpha = .55; for (let lon = Math.ceil(w * 2) / 2; lon <= e; lon += .5) { ctx.beginPath(); for (let lat = so; lat <= n; lat += .08) { const p = s.projection.project([lon, lat]); lat === so ? ctx.moveTo(...p) : ctx.lineTo(...p); } ctx.stroke(); } for (let lat = Math.ceil(so * 2) / 2; lat <= n; lat += .5) { ctx.beginPath(); for (let lon = w; lon <= e; lon += .08) { const p = s.projection.project([lon, lat]); lon === w ? ctx.moveTo(...p) : ctx.lineTo(...p); } ctx.stroke(); } ctx.globalAlpha = 1; } };
export const base: Layer = { id: "base", static: true, draw(ctx, s, now) { const labels: { x: number; y: number; width: number }[] = []; ctx.font = "11px Instrument Sans, sans-serif"; ctx.textAlign = "center"; getOdishaDistricts().features.forEach((feature) => { ring(feature.geometry).forEach((points) => path(ctx, points, s, now)); ctx.strokeStyle = s.theme.lineStrong; ctx.stroke(); const points = (feature.geometry.coordinates as [number, number][][])[0]!; const center: [number, number] = [points.reduce((v, p) => v + p[0], 0) / points.length, points.reduce((v, p) => v + p[1], 0) / points.length]; const [x, y] = s.projection.project(center); const width = ctx.measureText(feature.properties.district).width; if (!labels.some((label) => Math.abs(label.x - x) < (label.width + width) / 2 && Math.abs(label.y - y) < 14)) { ctx.fillStyle = s.theme.fg3; ctx.fillText(feature.properties.district, x, y); labels.push({ x, y, width }); } }); getOdishaState().features.forEach((feature) => { ring(feature.geometry).forEach((points) => path(ctx, points, s, now)); ctx.strokeStyle = s.theme.fg3; ctx.stroke(); }); } };
export const scale: Layer = { id: "scale", static: true, draw(ctx, s) { const x = s.width - 94, y = s.height - 24; ctx.strokeStyle = s.theme.fg3; ctx.beginPath(); ctx.moveTo(x, y); ctx.lineTo(x + 62, y); ctx.stroke(); ctx.font = "10px IBM Plex Mono, monospace"; ctx.fillStyle = s.theme.fg3; ctx.fillText("50 km", x + 31, y - 6); } };
let sprite: HTMLCanvasElement | null = null;
function blob(color: string) { if (sprite) return sprite; sprite = document.createElement("canvas"); sprite.width = sprite.height = 128; const c = sprite.getContext("2d")!; const g = c.createRadialGradient(64, 64, 2, 64, 64, 64); g.addColorStop(0, color); g.addColorStop(.45, color); g.addColorStop(1, "transparent"); c.fillStyle = g; c.fillRect(0, 0, 128, 128); return sprite; }
export const storms: Layer = { id: "storms", draw(ctx, s, now) { if (s.mode === "satellite") { ctx.globalAlpha = .3; } s.frame.cells.forEach((cell) => { const [x, y] = s.projection.project(cell.centroid); const size = Math.max(28, cell.radiusKm * 3) * (s.reduced ? 1 : 1 + Math.sin(now / 1200) * .04); const color = s.mode === "satellite" ? s.theme.observed : s.time <= 0 ? s.theme.observed : s.theme.forecast; if (s.mode === "radar" && !s.layers.radar || s.mode === "satellite" && !s.layers.satellite) return; ctx.globalAlpha = Math.min(.7, .22 + cell.reflectivityDbz / 100) * (s.decomposition && s.time > 0 ? .4 : 1); ctx.drawImage(blob(color), x - size / 2, y - size / 2, size, size); }); ctx.globalAlpha = 1; } };
let density: HTMLCanvasElement | null = null;
export const heatmap: Layer = { id: "heatmap", draw(ctx, s) { if (!s.layers.flashDensity) return; density ??= document.createElement("canvas"); density.width = 96; density.height = 64; const c = density.getContext("2d")!; const data = c.createImageData(96, 64); for (let y = 0; y < 64; y++) for (let x = 0; x < 96; x++) { const value = s.frame.flashDensity[Math.floor(y / 64 * s.frame.flashDensity.length)]?.[Math.floor(x / 96 * s.frame.flashDensity[0]!.length)] ?? 0; const i = (y * 96 + x) * 4; data.data.set([255, 176, 32, value * 115], i); } c.putImageData(data, 0, 0); ctx.globalAlpha = .5; ctx.drawImage(density, 0, 0, s.width, s.height); ctx.globalAlpha = 1; } };
export const corridors: Layer = { id: "corridors", draw(ctx, s, now) { if (!s.layers.corridors) return; s.frame.cells.forEach((cell) => { const alpha = s.selected && s.selected !== cell.id ? .25 : 1; ([15, 30, 60] as const).forEach((h) => { const c = corridorFor(cell, h, s.sensorOff.radar ? 1.35 : 1); ctx.fillStyle = s.theme.forecast; ctx.strokeStyle = s.theme.forecast; ctx.globalAlpha = alpha * .08; path(ctx, c.outer, s, now); ctx.fill(); ctx.save(); ctx.setLineDash([5, 4]); ctx.globalAlpha = alpha; path(ctx, c.outer, s, now); ctx.stroke(); ctx.restore(); ctx.globalAlpha = alpha * .16; path(ctx, c.inner, s, now); ctx.fill(); ctx.globalAlpha = alpha; ctx.lineWidth = 2; path(ctx, c.center, s, now); ctx.stroke(); const p = s.projection.project(c.center.at(-1)!); ctx.font = "10px IBM Plex Mono, monospace"; ctx.fillText(`+${h}`, p[0] + 5, p[1]); }); }); ctx.globalAlpha = 1; } };
export const labels: Layer = { id: "labels", draw(ctx, s, now) { s.frame.cells.forEach((cell) => { const [x, y] = s.projection.project(cell.centroid); ctx.fillStyle = s.theme.fg; ctx.font = "10px IBM Plex Mono, monospace"; ctx.fillText(cell.id, x + 10, y + 14); if (s.selected === cell.id) { ctx.strokeStyle = s.theme.fg; ctx.lineWidth = 1; ctx.beginPath(); ctx.arc(x, y, Math.max(10, cell.radiusKm * 1.5), 0, Math.PI * 2); ctx.stroke(); } }); } };
export const motion: Layer = { id: "motion", draw(ctx, s, now) { s.frame.cells.forEach((cell) => { const [x, y] = s.projection.project(cell.centroid); const a = (cell.motion.dirDeg - 90) * Math.PI / 180; ctx.strokeStyle = s.theme.fg2; ctx.beginPath(); ctx.moveTo(x, y); ctx.lineTo(x + Math.cos(a) * 18, y + Math.sin(a) * 18); ctx.stroke(); ctx.fillStyle = s.theme.fg2; ctx.font = "10px IBM Plex Mono, monospace"; ctx.fillText(`${Math.round(cell.motion.speedKmh)} km/h`, x + 6, y - 8); }); } };
export const assets: Layer = { id: "assets", draw(ctx, s, now) { if (!s.layers.assets) return; const data = getSyntheticAssets(); data.polylines.forEach((line) => { path(ctx, line.path, s, now, false); ctx.strokeStyle = s.theme.fg2; ctx.stroke(); }); data.points.forEach((asset) => { const [x, y] = s.projection.project(asset.lonLat); ctx.fillStyle = s.theme.fg2; ctx.font = "12px sans-serif"; ctx.fillText(({ school: "□", hospital: "+", airport: "✈", mine: "◆", event: "○", village: "•" } as Record<string, string>)[asset.type] ?? "•", x - 4, y + 4); }); } };
export const decomposition: Layer = { id: "decomposition", draw(ctx, s, now) { if (!s.decomposition) return; s.frame.cells.forEach((cell) => { const [x, y] = s.projection.project(cell.centroid); const d = cell.decomposition; ctx.fillStyle = d.growth > .5 ? s.theme.risk : s.theme.observed; ctx.globalAlpha = .8; ctx.beginPath(); ctx.arc(x, y, 7 + Math.abs(d.growth - .5) * 18, 0, Math.PI * 2); ctx.fill(); d.initiationSites.forEach((site) => { const p = s.projection.project(site); ctx.strokeStyle = s.theme.forecast; ctx.beginPath(); ctx.arc(p[0], p[1], s.reduced ? 8 : 8 + Math.sin(now / 500) * 3, 0, Math.PI * 2); ctx.stroke(); ctx.fillStyle = s.theme.forecast; ctx.font = "10px IBM Plex Mono, monospace"; ctx.fillText("New cell", p[0] + 10, p[1]); }); }); ctx.globalAlpha = 1; } };
